### ISSUE TITLE
This is a test issue.

### ISSUE THREAD

**Issue by russbuchanan** [scratch-fhir-profiles/CA-Core#1]
Information from the spreadsheet could be added here.  With a direct link to content (https://build.fhir.org/ig/scratch-fhir-profiles/CA-Core/profile-patient-definitions.html#Patient.identifier:JHN.value)

**Comment by russbuchanan** [comment]
This is a response.

**Comment by kensinn** [comment]
I agree with this approach.

**Comment by kensinn** [comment]
Could we also add a "patient-profile" label, enabling us to sort/filter issues/comments by resource?

**Comment by russbuchanan** [comment]
This would lead to a lot of tags but is doable if it is useful.
