### ISSUE TITLE
Practitioner_Binding_identifier.LN.type

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#12]
Reviewer: Finnie Flores

Organization: Canadian Institute for Health Information (CIHI)

Profile: Practitioner
Change Category: Binding
Element: identifier.LN.type

Rationale:

As this particular slice is specifc to LN, the identifier.type should be fixed to LN

Also, LN should be added to identifier-type value set

**Comment by russbuchanan** [comment]
Slicing removed in response to Issue #50. No longer applicable.
