### ISSUE TITLE
Organization_Binding_identifier.PRN.type

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#17]
Reviewer: Finnie Flores

Organization: Canadian Institute for Health Information (CIHI)

Profile: Organization
Change Type: Binding
Element: identifier.PRN.type

Rationale:

As this particular slice is specifc to PRN, the identifier.type should be fixed to PRN

**Comment by russbuchanan** [comment]
Please see binding information below.

![image](https://user-images.githubusercontent.com/15872739/61009946-76ee2b80-a342-11e9-91d0-cfff380637c7.png)

**Comment by russbuchanan** [comment]
Slicing removed in response to Issue #58. No longer applicable.
