### ISSUE TITLE
Organization_Binding_identifier.LN.type

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#18]
Reviewer: Finnie Flores

Organization: Canadian Institute for Health Information (CIHI)

Profile: Organization
Change Category: Binding
Element: identifier.LN.type

Rationale:

As this particular slice is specifc to LN, the identifier.type should be fixed to LN

Also, LN should be added to identifier-type value set

**Comment by russbuchanan** [comment]
Please see binding information below.

![image](https://user-images.githubusercontent.com/15872739/61009900-4d350480-a342-11e9-8c0a-5b463760dee0.png)

**Comment by lmckenzi** [comment]
Using pattern rather than fixed value is appropriate here.  
It would actually be good to propose adding LN to HL7's value set and deprecating the MD code (which is a subset of LN)

**Comment by russbuchanan** [comment]
Slicing removed in response to Issue #58.  No longer applicable.
