### ISSUE TITLE
Location_Binding_identifier.PRN.type

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#19]
Reviewer: Finnie Flores

Organization: Canadian Institute for Health Information (CIHI)

Profile: Location
Change Category: Binding
Element: identifier.PRN.type

Rationale:

As this particular slice is specifc to PRN, the identifier.type should be fixed to PRN

**Comment by russbuchanan** [comment]
See current binding information below.

![image](https://user-images.githubusercontent.com/15872739/61009389-81a7c100-a340-11e9-9bc0-5a09308e8d4b.png)

**Comment by russbuchanan** [comment]
Slicing removed in response to Issue #52 . No longer applicable.
