### ISSUE TITLE
Location_Binding_identifier.LN.type

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#20]
Reviewer: Finnie Flores

Organization: Canadian Institute for Health Information (CIHI)

Profile: Location
Change Category: Binding
Element: identifier.LN.type

Rationale:

As this particular slice is specifc to LN, the identifier.type should be fixed to LN

Also, LN should be added to identifier-type value set

**Comment by russbuchanan** [comment]
![image](https://user-images.githubusercontent.com/15872739/61009151-b8c9a280-a33f-11e9-9be7-60cc59355ab5.png)

**Comment by russbuchanan** [comment]
Slicing removed in response to Issue #52 . No longer applicable.
