### ISSUE TITLE
Patient_Cardinality_patient.name.id

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#32]
Submitter: Harsh Sharma
Organization: Alberta Health Services

Profile: Patient
Change Category: Cardinality
Element: patient.name.id

Rationale: Change card. To 0..*

Feedback: In Canada we have, Internal ID, External ID, PHNs, MRNs, RCMP ID, DoD ID etc.

**Comment by kensinn** [comment]
The Patient.name.id is inherited from the base element definition "element.id", and is intended only for internal references within/between resources. It's even more specific that that, pointing to a specific Patient.name element by reference. https://www.hl7.org/fhir/element-definitions.html#Element.id

For patient identification, such as internal ID, extenal ID, MRNs, etc, you'll want to use Patient.identifier, which is 1..* in CA-Core (and also 1..* in US-Core).

**Comment by harshsharma09** [comment]
> 
> 
> The Patient.name.id is inherited from the base element definition "element.id", and is intended only for internal references within/between resources. It's even more specific that that, pointing to a specific Patient.name element by reference. https://www.hl7.org/fhir/element-definitions.html#Element.id
> 
> For patient identification, such as internal ID, extenal ID, MRNs, etc, you'll want to use Patient.identifier, which is 1..* in CA-Core (and also 1..* in US-Core).

Hi Ken, 
Thanks for the comment. This is very helpful.

**Comment by sheridancook** [comment]
Hi @harshsharma09 , thanks for closing the loop on this one. Should we close it out?

**Comment by harshsharma09** [comment]
> 
> 
> Hi @harshsharma09 , thanks for closing the loop on this one. Should we close it out?
@sheridancook yes please. Is there a way to archive the comments?

**Comment by sheridancook** [comment]
> > Hi @harshsharma09 , thanks for closing the loop on this one. Should we close it out?
> > @sheridancook yes please. Is there a way to archive the comments?

@harshsharma09 - Hi Harsh, Closed issues can still be accessed in the issue log, they don't get deleted. There are a couple of ways to access them. Once you're in the issue log page you can change your filter to "is:issue is:closed", right below the filter search box you should also see  a header that states "44 issues open 4 issues closed" if you click on the number of issues closed it'll also bring you there. 

Hope this helps. Thanks for sending in your suggestions btw, it's hard to get volunteer reviewers early on so we need all the help and perspectives that we can get!

**Comment by harshsharma09** [comment]
@sheridancook Hi Sheridan, Thanks for your help. I really appreciate. :) I am still learning things about FHIR. I hope, i can add some value from my past work experience as certified HL7 V2.7 control specialist, V3 RIM Specialist.
