### ISSUE TITLE
Patient.id

### ISSUE THREAD

**Issue by michel-boivin** [scratch-fhir-profiles/CA-Core#35]
What are the rules associated with Patient.id ? 
For example :
•	The Patient.id  is generated by a FHIR resource server (canadian juridictional or regional ?)
•	The Patient.id  is globally unique across other FHIR resource servers.
•	The Patient.id  is only used for internal machine processing (never displayed nor printed for human use).

**Comment by kensinn** [comment]
Patient.id would be assigned by the FHIR server storing that resource, whether that is a national system, provincial/territorial, or even a local EMR system. The Patient.id is only unique on that FHIR server storing that Patient resource.

Please see https://www.hl7.org/fhir/resource.html#id for additional details on how all resource.id elements are used (applies to Patient.id, Practitioner.id, Medication.id -- anything in FHIR will have a .id). I don't believe CA-Core or US-Core or IPS are making any amends or additional restrictions/rules beyond the base FHIR rules around how resource.id is used.

**Comment by michel-boivin** [comment]
In fact [https://www.hl7.org/fhir/resource.html#id](url) provides clear information on the id's mechanism.

**Comment by kensinn** [comment]
Hi Michel,

Is this issue considered closed? Or do we need additional discussion? Thanks!
