### ISSUE TITLE
Patient_Documentation_patient.name_invariant

### ISSUE THREAD

**Issue by kensinn** [scratch-fhir-profiles/CA-Core#37]
Submitter: Harsh Sharma
Organization: Alberta Health Services

Profile: Patient
Change Category: Documentation
Element: patient.name

Rationale: US-Core has an invariant "us-core-8: Patient.name.given or Patient.name.family or both SHALL be present", to allow implementations to provide patient.name (1..1), but allow for either patient.name.given (0..*) or patient.name.family (0..1) to be empty, but preventing both from being empty. 

Feedback: CA-Core should attach a similar invariant rule for Patient.name.given + Patient.name.family, particularly to support incomplete data as well as mononym culture use cases.

**Comment by sheridancook** [comment]
Hi @harshsharma09, see the following commit that addresses the changes you proposed to use an equivalent ca-core-8 invariant on patient.name to better align with Canadian implementations and US Core: https://github.com/scratch-fhir-profiles/CA-Core/commit/964293b99c5c8c4f0a211f15176113fb932d8854 . Let us know if that's what you were looking for!

**Comment by harshsharma09** [comment]
@sheridancook Hi Sheridan, I agree with @kensinn comment. Yes, i was looking for the same logic. Thanks

**Comment by sheridancook** [comment]
This change was approved and committed (964293b)[https://github.com/scratch-fhir-profiles/CA-Core/commit/964293b99c5c8c4f0a211f15176113fb932d8854] and will be closed
