### ISSUE TITLE
Patient_Editorial Content_identifier.extension.data-absent-reason

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#4]
Reviewer: Ken Sinn

Organization: eHealth Ontario

Profile: Patient
Change Category: Editorial Content
Element: identifier.extension.data-absent-reason

Rationale:

CA-Core and US-Core do not explicitly define, but noted that data absent reason should be provided if known (http://build.fhir.org/ig/scratch-fhir-profiles/CA-Core/general-guidance.html#must-support) - but does not go into explicit detail on how this should be accomplished.
Suggest that a link to the Data Absent Reason extension (https://www.hl7.org/fhir/extension-data-absent-reason.html)  be provided in the Must-Support section of the Implementation Guide.

**Comment by sheridancook** [comment]
Changes above were made to improve alignment with US Core. The data absent extension was added to the artifact list and a note was added to the Must Support page content for the patient profile. Details of the commit can be found here: https://github.com/scratch-fhir-profiles/CA-Core/commit/7788e23a6def8d5f8075da1f85986d4601cdd67b . 

@kensinn I'm going to close this particular issue (patient-focused) but when you're back, I'd love your thoughts on if we should include the same page content note in other profiles.
