### ISSUE TITLE
Location_Slicing_identifier

### ISSUE THREAD

**Issue by kensinn** [scratch-fhir-profiles/CA-Core#52]
Reviewer: Ken Sinn
Organization: eHealth Ontario

Location.identifier.type slicing:
CA-Core: Location.identifier (1..*) is sliced for:
	• PRN (Provider Number, identifier.type=PRN, 0..*)
	• LN (Licence Number, identifier.type=LN, 0..*)
	• OTH (Doctor's Number, identifier.type=DN, 0..*)
	• Unsliced
US-Core: Location.identifier (0..*) not MustSupport, no slicing

Recommendation is to leave Location.identifier unsliced, since it's not clear if there is a pan-Canadian identifier consensus on how to identify a location using a Business Identifier. This would have better alignment with US-Core implementations, unless there is a clear use-case for location identifier (how do you identify the sites of a multi-site/campus hospital? Are they all licensed?) Additionally, this level of granularity seems to be too much for a pan-Canadian baseline, and may be left to jurisdictions to handle, based on jurisdictional location identification/management.

**Comment by russbuchanan** [comment]
Discussion on 8/16/2019 call:
This is similar to Practitioner discussion in Issue #50.

**Decision of group on call:** Remove slicing until there is clear requirement. Implement the change and allow the group to respond.

**Comment by russbuchanan** [comment]
Committed proposed change.
