### ISSUE TITLE
Location_Cardinality_identifier

### ISSUE THREAD

**Issue by kensinn** [scratch-fhir-profiles/CA-Core#53]
Reviewer: Ken Sinn
Organization: eHealth Ontario

CA-Core: Location.identifier (1..*) + MustSupprt
US-Core: Location.identifier (0..*) + not MustSupport

Is there a good reason to have a Location.identifier as MustSupport or Mandatory? Is there a consistent and guaranteed identifier in every jurisdiction, or a pan-Canadian location identifier? Otherwise this seems to be an unnecessary deviation from US-Core.

Recommendation to change Location.identifier to (0..*) and not MustSupport unless there is a pan-Canadian concensus on always having a business identifier; at most, maybe MustSupport with (0..*) cardinality.

**Comment by russbuchanan** [comment]
Discussion on 8/16:
Location pertains to a situation where an Organization has multiple different sites.  Do these always have their own identifiers?
Suggestion to loosen constraint for now was supported on call.
Next step is to loosen the constraint.

**Comment by russbuchanan** [comment]
Committed proposed change.
