### ISSUE TITLE
Organization_Slicing_identifier

### ISSUE THREAD

**Issue by kensinn** [scratch-fhir-profiles/CA-Core#58]
Reviewer: Ken Sinn
Organization: eHealth Ontario

Organization.identifier.type slicing:
CA-Core: Organization.identifier (1..) is sliced for:
• PRN (Provider Number, identifier.type=PRN, 0..)
• LN (Licence Number, identifier.type=LN, 0..)
• OTH (0..)
• Unsliced
US-Core: Organization.identifier (1..*) MustSupport, no slicing

Recommendation is to leave Organization.identifier unsliced, since it's not clear if there is a pan-Canadian identifier consensus on the types of Business Identifiers used for Organizations. This would have better alignment with US-Core implementations, unless there is a clear for organization identifier type. Additionally, this level of granularity seems to be too much for a pan-Canadian baseline, and may be left to jurisdictions to handle, based on jurisdictional organization identification/management.

Are there any situations where an Organization identifier is unavailable?

**Comment by russbuchanan** [comment]
Decision to remove slicing on profiling meeting on 8/16.

**Comment by russbuchanan** [comment]
Slicing removed, committed to repository.

Note: Organization.identifier is still mandatory, MustSupport = True without a terminology binding.  Is this appropriate?

**Comment by russbuchanan** [comment]
Question above is subject of Issue #59 (open).  Closing this issue.
