### ISSUE TITLE
Patient_Cardinality_name.given, name.family

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#6]
Reviewer: Ken Sinn

Organization: eHealth Ontario

Profile: Patient
Change Category: Cardinality
Element: name.given, name.family

Rationale:

CA-Core name.given (1..*) and name.family (1..1) cardinalities are not guaranteed to exist, based on historical data in Ontario's patient registry. There are also some cultures that only use a single name (mononym), and some hospitals have handled this by storing and duplicating the single name in both the name.family and name.given fields.
For comparison, US-Core uses name.given (0..*) and name.family (0..1) with an Invariant rule requiring at least one of either name.given or name.family (us-core-8 on https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-patient-definitions.html#Patient.name). IPS is in the process of realigning name.given and name.family to the same US-core cardinalities. Ontario's Provincial Client Registry also uses name.given (0..*) and name.family (0..1).
Recommendation is for CA-Core to adopt the same cardinality and invariant rule as US-Core.

**Comment by sheridancook** [comment]
Hi Ken, see the following commit that addresses the changes referenced above to better align with Canadian implementations and US Core: https://github.com/scratch-fhir-profiles/CA-Core/commit/964293b99c5c8c4f0a211f15176113fb932d8854
