### ISSUE TITLE
Medication_Ingredient

### ISSUE THREAD

**Issue by igorsirkovich** [scratch-fhir-profiles/CA-Core#61]
I don't think Medication.ingredient should be marked as "Must Support". This might have to be marked as "Must Support" for some implementations, but not for all.

**Comment by sheridancook** [comment]
@Xperterra  Hi Igor, thanks for the additional insight. Can you elaborate on some of the situations where implementations where it is/isn't applicable to consider ingredient a must support?

What's the best way to handle? Remove the Must Support flag and allow future profiles that profile on top of the CA Core to choose whether it should be must support?

**Comment by russbuchanan** [comment]
Discussion on 9/13: DHDR doesn't support ingredients - example of a use case where it wasn't needed.  Ken: MustSupport puts onus on clients to store an ingredient received.  Should be determined for each use case and probably not a requirement.  Decision to implement change pending new information from discussion about CCDD.

**Comment by russbuchanan** [comment]
Implemented and committed change to repository.
