### ISSUE TITLE
Medication_Code_Text

### ISSUE THREAD

**Issue by igorsirkovich** [scratch-fhir-profiles/CA-Core#62]
I'm not sure if 1000 characters would be sufficient for a full description of a compound medication - the one that doesn't have a CCDD code or DIN and should display a full label created by a pharmacist instead.

**Comment by russbuchanan** [comment]
Discussion 9/13, about string length and mandatory (1:1).  Proposal to remove string length, change to optional element (0:1).  No opposition to proposal, decision to implement change.
(Leave as MustSupport).

**Comment by russbuchanan** [comment]
Implemented and committed change to repository.
